[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; object-src 'none'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; object-src 'none'"
